### ISSUE TITLE
Helm chart incorrectly encodes extraRules

### ISSUE THREAD

**Issue by brettmorien** [indeedeng-alpha/harbor-container-webhook#13]
The default installation values for `extraRules` get encoded to yaml as a literal `[]` in the config map. This makes it not parseable and unusable. We haven't been able to find a substitute value which encodes correctly. I'm presuming this is because it is stacked after the `rules:` section.

https://github.com/indeedeng-alpha/harbor-container-webhook/blob/main/deploy/charts/harbor-container-webhook/templates/config.yaml#L21

```
...
rules:
  - checkUpstream: false
    matches:
    - '^docker.io'
    name: image-proxy
    replace: upstream:30003/dockerhub
[]
```
