### ISSUE TITLE
Make the app tolerant to having no quotes around matches in configmap

### ISSUE THREAD

**Issue by brettmorien** [indeedeng-alpha/harbor-container-webhook#14]
We specify a match for ^docker.io to the helm chart values through Terraform, but it has issues escaping the single quotes the webhook application is expecting around the match in the config map. It seems very difficult to get a yaml value with a single quote around it. Can the config file reader get away with not having the value quoted?

Terraform:
```
     "rules" : [
        { ...
          matches : ["^docker.io"]
        ... }
```
Configmap:
```
rules:
  - matches:
    - ^docker.io
```
Terraform:
```
     "rules" : [
        { ...
          matches : ["'^docker.io'"]
        ... }
```
Configmap:
```
rules:
  - matches:
    - '''^docker.io'''
```

**Comment by cnmcavoy** [comment]
I used single quotes as the example, but the webhook is using the Golang std yaml parser. Double quotes work, as well as unquoted strings.

For example, I took the config in the `hack/` dir and unquoted the regular expressions and the webhook was able to start:
```yaml
port: 9443
certDir: "./hack/certs"
healthAddr: ":8080"
metricsAddr: ":8081"
rules:
  - name: 'docker.io rewrite rule'
    # image refs must match at least one of the rules, and not match any excludes
    matches:
      - ^docker.io
    excludes:
      # for example, exclude ubuntu from harbor's proxy cache
      - ^docker.io/(library/)?ubuntu:.*$
    replace: 'harbor.example.com/dockerhub-proxy'
    checkUpstream: false
  - name: 'docker.io ubuntu rewrite rule'
    # image refs must match at least one of the rules, and not match any excludes
    matches:
      - '^docker.io/(library/)?ubuntu:.*$'
    replace: 'harbor.example.com/ubuntu-proxy'
    checkUpstream: true # tests if the manifest for the rewritten image exists
```
Can you share an example config that the webhook won't load?

**Comment by brettmorien** [comment]
Sorry for the noise here. There were multiple factors at play, and I think I just verified this isn't an issue. The config map seems to work correctly with no quotations.
```
rules:
  - checkUpstream: false
    matches:
    - ^docker.io
```
