### ISSUE TITLE
tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by armenr** [indeedeng-alpha/harbor-container-webhook#22]
## Use-Case

We're running harbor internally. We use the bitnami helm chart, and we pass the following values:

```
externalURL: harbor.harbor.svc.cluster.local
service:
  type: ClusterIP
nginx:
  tls:
    commonName: harbor.harbor.svc.cluster.local
adminPassword: <REDACTED>
commonLabels:
  goharbor.io/harbor-container-webhook-disable: 'true'
persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 800Gi
      accessModes:
        - ReadWriteOnce
postgresql:
  architecture: replication
  readReplicas:
    extendedConfiguration: |
      max_connections = 1024
  primary:
    extendedConfiguration: |
      max_connections = 1024
```

**We** are fine with using the self-signed certificate that gets generated by the default installation - specifically for the nginx proxy - but it seems the mutating webhook is not happy with the self-signed cert (and cannot be configured to accept/skip that).

## Logs:

```
harbor/harbor-mutating-webhook-harbor-container-webhook-79fc86f85c699r[harbor-container-webhook]: 2023-07-31T15:26:24Z	INFO	mutator	skipping rewriting "491919724562.dkr.ecr.us-west-2.amazonaws.com/redacted_repo:release-6.6.1-0bfbb1f" to "harbor.harbor.svc.cluster.local/ecr/redacted_repo:release-6.6.1-0bfbb1f", could not fetch image manifest: Get "https://harbor.harbor.svc.cluster.local/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority; Get "https://harbor.harbor.svc.cluster.local/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
harbor/harbor-mutating-webhook-harbor-container-webhook-79fc86f85c699r[harbor-container-webhook]: 2023-07-31T15:26:24Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/webhook-v1-pod", "code": 200, "reason": "no updates", "UID": "40c4d6f5-4b34-457f-94ef-a5d655b07079", "allowed": true}
```

I may be k8s+tls illiterate here, but what can we do to work around this, or otherwise address it?
